---
title: "INFO511 Fall 2024 Project Proposal"
subtitle: "Exploring evoling electric vehicle charging efficiency"
author: 
  - name: "ChilePepper"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "A review of all three datasets, in Python, is provided below with descriptions of the variables studied using .head() and .info(). The three datasets considered for the project were (i) electric vehicle (EV) Charging, (ii) an analysis of Spotify Data, and (iii) an assessment of Mobile User Data. The reason and justification for why the team would like to work with these three datasets is provided herein. The team has agreed to select the EV Charging Dataset for the project out of an interest to explore that evolving technical space and build predictive models for charging efficiency."

format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import warnings
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

```

## Introduction to the Data

```{python}
#| label: load-dataset
#| message: false

url = "https://raw.githubusercontent.com/INFO-511-F24/final-project-ChilePeppers/main/data/ev_charging_patterns.csv"
ev_charging  = pd.read_csv(url)

url = "https://raw.githubusercontent.com/INFO-511-F24/final-project-ChilePeppers/main/data/Spotify_Most_Streamed_Songs.csv"

Spotify_db = pd.read_csv(url)

url = "https://raw.githubusercontent.com/INFO-511-F24/final-project-ChilePeppers/main/data/Mobile_user_behavior_dataset.csv"

mobile_data = pd.read_csv(url)
```

## Dataset 1 - Electric Vehicle Charging

-   Source of Data: https://www.kaggle.com/datasets/valakhorasani/electric-vehicle-charging-patterns

-   Description of Observations: This dataset provides a comprehensive analysis of electric vehicle (EV) charging patterns and user behavior. It contains 1,320 samples of charging session data, including metrics such as energy consumption, charging duration, and vehicle details. Each entry captures various aspects of EV usage, allowing for insightful analysis and predictive modeling.

-   Ethical Concerns: The dataset has user IDs and specific charging station locations, which means there’s a chance it could reveal patterns in people’s movements and behaviors. To protect privacy, it’s important to keep user IDs anonymous and possibly generalize location data so individuals can’t be tracked. Researchers also need to handle this information carefully and follow data protection rules to use it responsibly.

-   Question:

    1.  How do vehicle model, user type, and starting state of charge influence the cost and duration of EV charging sessions at public stations?
    2.  Exploring energy consumption and charging behaviors
    3.  Building predictive models for charging efficiency

-   Importance:Understanding the costs and durations associated with different EV types and user profiles can help:

    -   Consumers make cost-effective charging decisions.
    -   Charging service providers optimize station usage and pricing strategies by identifying patterns in energy demand and time usage.

-   Hypothesis:

    -   Vehicle Model: Larger battery capacity models will have longer charging times and higher costs.
    -   User Type: Frequent users (like commuters) may incur lower costs per session due to shorter, more regular charging patterns.
    -   Starting State of Charge: Lower starting charge levels are expected to lead to longer and more costly charging sessions.

-   Variable Types: Categorical Variables: Vehicle Model, User Type Quantitative Variables: Charging Cost (USD), Charging Duration (hours), State of Charge (Start %)

## Glimpse of the Data: Dataset 1 - EV Charging

```{python}

print(f'Table 1: EV Charging Dataset:\n\n')
ev_charging.head()

```

```{python}
print(f'Table 2: EV Charging Dataset: Variables and their Type (Dtype)\n\n')

ev_charging.info()
```

## Analysis Plan EV Charting Dataset

The EV charging dataset comprises 20 columns, 10 object variables and 10 float64 variables. The analysis plan will be completed in three steps to answer the questions and hypothesis stated above. 

Step 1: A graphical analysis of the dataset 

Step 2: A statistical analysis of the dataset using (i) analysis of variance and (ii) mullivariable regression to understand patterns within the data.

Step 3: Build a predictive model from the data to understand and predict trends. 

## Dataset 2 - Spotify User Data 

* Source of the Data:

https://www.kaggle.com/datasets/abdulszz/spotify-most-streamed-songs
This dataset originates from Apple's and Spotify's public API. Each track’s streaming metrics and musical attributes could have been aggregated from streaming services' API or charts, though specific documentation would be necessary to confirm.

* Description of Observations:
Observations include details on each song’s title, artist(s), release date, and musical attributes (e.g., tempo, key, mode, acousticness, danceability). There are also metrics related to streaming, such as chart ranks and playlist placements on various platforms.

* Ethical Concerns:
The primary ethical concern is the potential for data bias. Since popular songs are more likely to be Western or English-language songs, this could lead to cultural or genre bias in the analysis. Furthermore, if the data includes rankings or metrics derived from proprietary algorithms, care should be taken to avoid misuse or misinterpretation of these rankings.

* Question: 
How do musical attributes (such as tempo, energy, and valence) affect a song’s popularity on Spotify as measured by the number of streams and inclusion in playlists?

* Importance: 
Understanding the relationship between musical attributes and popularity can be valuable for artists, producers, and streaming platforms to optimize song characteristics for a wider audience reach.

* Hypothesis: 
Higher energy and danceability correlate with higher popularity metrics, as listeners may prefer upbeat and energetic tracks.

* Variable Types:
Categorical: Key, mode, release date
Quantitative: Streams, danceability, valence, energy, acousticness, instrumentalness


## Glimpse of the Data: Dataset 2: Spotify Dataset

```{python}
print(f'\n\nTable 3: Spotify Dataset - Column Summary:\n\n')
Spotify_db.head()

```

```{python}
print(f'\n\nTable 4: Spotify Dataset - Variables and Data Type (Dtype) Summary:\n\n')

Spotify_db.info()


```


## Analysis Plan Spotify Dataset

The Spotify User dataset comprises 25 columns, 8 object variables and 17 into64 variables. The analysis plan will be completed in three steps to answer the questions and hypothesis stated above. 

Step 1: Dataset cleanup using Pandas data wranging tools and a graphical analysis of the dataset 

Step 2: A statistical analysis of the dataset using (i) analysis of variance and (ii) mullivariable regression to understand patterns within the data.

Step 3: Build a predictive model from the data to understand and predict trends. 


## Dataset 3 - Mobile user Behavior

* source of Data: https://www.kaggle.com/datasets/valakhorasani/mobile-device-usage-and-user-behavior-dataset

* Description of Observation: This dataset provides a comprehensive analysis of mobile device usage patterns and user behavior classification. It contains 700 samples of user data, including metrics such as app usage time, screen-on time, battery drain, and data consumption. Each entry is categorized into one of five user behavior classes, ranging from light to extreme usage, allowing for insightful analysis and modeling.
*  Ethical Concerns: The Mobile Device Usage and User Behavior dataset raises potential privacy concerns, as it includes detailed behavioral metrics that could reveal patterns of individual users if personally identifiable information were present. Ensuring that data is anonymized and securely stored is essential to protect user privacy. Additionally, responsible analysis is important to avoid misinterpreting or stereotyping user behavior, which could lead to biased conclusions or inappropriate applications of the findings.

* Question: 
Predicting Battery Drain in Mobile Devices 

* Importance: 
Understanding and predicting battery usage is essential for improving device performance, enhancing user experience, and guiding power optimization strategies.


* Variable Types:
Categorical: Device Model,Operating System, Number of Apps Installed, Age, Gender
Quantitative: App Usage Time, Screen On Time, Data Usage


```{python}

print(f'\n\nTable 5: Mobile User Dataset, Column Summary:\n\n')
mobile_data.head()

```

```{python}
print(f'Table 6: Mobile User Dataset - Data Type (Dtype) Summary:\n\n')

mobile_data.info()

```


Step 1: Dataset cleanup and a graphical analysis of the dataset.

Step 2: A statistical analysis of the dataset using (i) analysis of variance and (ii) mullivariable regression to understand patterns within the data.

Step 3: Build a predictive model from the data to understand and predict trends. 